### ISSUE TITLE
Cuda Failure to compile mk 2 

### ISSUE THREAD

**Issue by unrealwill** [wsmoses/Enzyme#268] opened 2021-08-03 16:47 UTC
Hello, 

Starting from a working example copy pasted from https://enzyme.mit.edu/getting_started/CUDAGuide/
I tried to remove the parameter nTimeStep of iter. And it then fails to compile with : 

`clang-12: ../Enzyme/EnzymeLogic.cpp:1512: const AugmentedReturn& EnzymeLogic::CreateAugmentedPrimal(llvm::Function*, DIFFE_TYPE, const std::vector<DIFFE_TYPE>&, llvm::TargetLibraryInfo&, TypeAnalysis&, bool, const FnTypeInfo&, std::map<llvm::Argument*, bool>, bool, bool, bool, bool): Assertion `0 && "attempting to differentiate function without definition"' failed.`

` bugCuda.cu`

```
#include <stdio.h>
#include <iostream>
using namespace std;

__device__ int enzyme_dup;
__device__ int enzyme_out;
__device__ int enzyme_const;

// We move the body of collide into a separate device function collide_body to allow us
// to pass collide_body to various differentiation methods. This is necessary as differentiation
// can only be done on device, not global kernel functions.


__device__
void collide_body( float* src, float* dst) {
    size_t idx = threadIdx.x;
    if (idx < 100) {
        dst[idx] = src[idx] * src[idx] - 3 * src[idx];
    }
}

// GPU Kernel
__global__
void collide( float* src,  float* dst) {
    collide_body(src, dst);
}

// Wrapper CPU function which calls kernel
__attribute__((noinline))
void kern( float* src, float* dst) {
    collide<<<1, 100>>>(src,dst);
}

// Main CPU code that calls wrapper function
void iter( /*int nTimeSteps,*/ float* src, float* dst) {
    for (unsigned int i=0; i< /*nTimeSteps/2*/ 1; i++) {
        kern(src, dst);
        kern(dst, src);
    }
}

// A function similar to __enzyme_autodiff, except it only calls the augmented forward pass, returning
// a tape structure to hold any values that may be overwritten and needed for the reverse.
template <typename... Args>
__device__ void* __enzyme_augmentfwd(Args...);

// A function similar to __enzyme_autodiff, except it only calls the revese pass, taking in the tape
// as its last argument.
template <typename... Args>
__device__ void __enzyme_reverse(Args...);

// A wrapper GPU kernel for calling the forward pass of collide. The wrapper code stores
// the tape generated by Enzyme into a unique location per thread
__global__ void aug_collide( float* src, float* dsrc, float* dst, float* ddst, void** tape)
{
    size_t idx = threadIdx.x;
    tape[idx] = __enzyme_augmentfwd((void*)collide_body,
                                                                                               src, dsrc,
                                                                                              dst, ddst);
}

// A wrapper GPU kernel for calling the reverse pass of collide. The wrapper code retrieves
// the corresponding tape per thread being executed.
__global__ void rev_collide( float* src, float* dsrc ,float* dst, float* ddst, void** tape)
{
    size_t idx = threadIdx.x;
    __enzyme_reverse((void*)collide_body,
                                                                   src, dsrc,
                                                                  dst, ddst,
                                                                     tape[idx]);
}

// The augmented forward pass of the CPU kern call, allocating and returning
// tape memory  needed to compute the reverse pass. This calls a augmented collide
// GPU kernel, passing in a unique 8-byte location to store the tape.
void* aug_kern(float* src, float* dsrc,  float* dst, float* ddst) {
    void** tape;
    cudaMalloc(&tape, sizeof(void*) * /*total number of threads*/100);
    aug_collide<<<1, 100>>>(src, dsrc,dst, ddst, tape);
    return (void*)tape;
}

// The reverse pass of the CPU kern call, using tape memory passed as the
// last argument. This calls a reverse collide GPU kernel.
void rev_kern( float* src, float* dsrc, float* dst, float* ddst, void* tape) {
    rev_collide<<<1, 100>>>( src, dsrc,dst, ddst, (void**)tape);
    cudaFree(tape);
}

// Here we register the custom forward pass aug_kern and reverse pass rev_kern
void* __enzyme_register_gradient_kern[3] = { (void*)kern, (void*)aug_kern, (void*)rev_kern };


template <typename... Args>
void __enzyme_autodiff(Args...);

void grad_iter( /*int nTimeSteps,*/  float* src, float* dsrc, float* dst, float* ddst) {
  __enzyme_autodiff(iter, /* enzyme_const, nTimeSteps,*/
                                                          enzyme_dup,    src, dsrc,
                                                          enzyme_dup,  dst, ddst);
}

int main() {
    int n = 100;
    float* v ;
    float* dv ;

    float* out ;
    float* dout ;

    cudaMalloc(&v, n* sizeof(float));
    cudaMalloc(&dv, n* sizeof(float));

    cudaMalloc(&out, n* sizeof(float));
    cudaMalloc(&dout, n* sizeof(float));

    float *h_v = new float[n];
    float *h_dv = new float[n];
    float *h_out = new float[n];
    float *h_dout = new float[n];
    for( int i = 0 ; i < n ; i++)
    {
      h_v[i] = i+1;
      h_dv[i] = 0.0;
      h_out[i] = 0.0;
      h_dout[i]= 1.0;
    }

    cudaMemcpy(v,h_v, n*sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(dv,h_dv, n*sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(out,h_out, n*sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(dout,h_dout, n*sizeof(float), cudaMemcpyHostToDevice);
     cudaDeviceSynchronize();
     //iter( 4, v, out );
     grad_iter(v,dv,out,dout);
     //cudaDeviceSynchronize();
    cudaMemcpy(h_out, out, n*sizeof(float), cudaMemcpyDeviceToHost);
    cudaMemcpy(h_dv, dv, n*sizeof(float), cudaMemcpyDeviceToHost);
    cudaDeviceSynchronize();
    for( int i = 0 ; i < n ; i++)
    {
      cout << "out [ " << i << " ] = " << h_out[i] << endl;
      cout << "dv [ " << i << " ] = " << h_dv[i] << endl;
    }

}
```

Compilation with : 
`clang bugCuda.cu -lstdc++ -Xclang -load -Xclang /usr/local/lib/ClangEnzyme-12.so -O2 -fno-vectorize -fno-unroll-loops -fPIC --cuda-path=/home/username/cuda-10.1  --cuda-gpu-arch=sm_35 -lcudart -L/home/username/cuda-10.1/lib64 -o bugCuda
`

**Comment by unrealwill** [comment] 2021-08-03 22:07
The bug is probably in the custom gradient registration.
Because if I'm calling the augmented kernel and reverse kernel manually, it works fine.

```
//The following modification to the above code works fine.

// Main CPU code that calls wrapper function
void iter( /*int nTimeSteps,*/ float* src, float* dst) {
    //for (unsigned int i=0; i< /*nTimeSteps/2*/ 1; i++) {
        kern(src, dst);
        kern(dst, src);
    //}
}
void* __enzyme_register_gradient_kern[3] = { (void*)kern, (void*)aug_kern, (void*)rev_kern };

void grad_iter( /*int nTimeSteps,*/  float* src, float* dsrc, float* dst, float* ddst) {

 //__enzyme_autodiff(iter, src, dsrc,  dst, ddst); //This doesn't work

    void* tape0 = aug_kern( src,dsrc,dst,ddst );
    void* tape1 = aug_kern( dst,ddst ,src,dsrc);
    rev_kern(src,dsrc,dst,ddst,tape1);
    rev_kern(src,dsrc,dst,ddst,tape0);
}
```

**Comment by wsmoses** [comment] 2021-08-08 23:10
Duplicate of #267

**Closed by wsmoses** 2021-08-08 23:10 UTC

**Comment by unrealwill** [comment] 2021-08-09 09:33
This bug doesn't use constant arguments : I have removed them so that all arguments are active which make it a simpler case that should work.
This bug appeared as I tried to figure a workaround bug #267
